CHROMATIC = "Chromatic Orb"
ALCHEMY = "Orb of Alchemy"
ALTERATION = "Orb of Alteration"
DIVINE = "Divine Orb"
REGRET = "Orb of Regret"
PRISM = "Gemcutter's Prism"
ORB_OF_SCOURING = "Orb of Scouring"
CHAOS = "Chaos Orb"
VAAL_ORB = "Vaal Orb"
EXALTED_ORB = "Exalted Orb"
CHISEL = "Cartographer's Chisel"
FUSING = "Orb of Fusing"
TRANSMUTE= "Orb of Transmutation"
AUGMENT="Orb of Augmentation"
CHANCE='Orb of Chance'
JEWELLERS='Jeweller\'s Orb'
SCOUR='Orb of Scouring'
BAUBLE='Glassblower\'s Bauble'
WHETSTONE='Blacksmith\'s Whetstone'
try:
    from secrets import ssid as real_ssid

    ssid = real_ssid
except ImportError as e:
    print(e)
    print("Please set ssid in secrets.py")
    with open("secrets.py", "w") as f:
        f.write("ssid=")
    ssid = ""
hard_currency = [
    ALTERATION,
    ALCHEMY,
    "Chaos Orb",
    "Vaal Orb",
    "Warlord's Exalted Orb",
    DIVINE,
    "Exalted Orb",
    "Exalted Shard",
    FUSING,
    "Jeweller's Orb",
    "Awakened Sextant",
    "Prime Sextant",
    PRISM,
    "Regal Orb",
    "Mirror Shard",
    "Stacked Deck",
    "Mirror of Kalandra",
    CHISEL,
    "Orb of Unmaking",
    "Awakener's Orb",
    "Crescent Splinter",
]
price_in = [
    # "Orb of Alteration",
    # "Orb of Alchemy",
    "Chaos Orb",
    # "Vaal Orb",
    # "Divine Orb",
    # "Exalted Orb",
    # "Mirror Shard",
    # "Mirror of Kalandra",
]

currency_shards = {
    "House of Mirrors": ((1 / 9), "Mirror of Kalandra"),
    "Seven Years Bad Luck": (1 / 13, "Mirror Shard"),
    "Unrequited Love": (19 / (20*16), "Mirror of Kalandra"),
    "The Sephirot": (11 / 10, "Divine Orb"),
    "The Saint's Treasure": (2 / 10, EXALTED_ORB),
    "The Inventor": (10 / 6, VAAL_ORB),
    "The Innocent": (40 / 10, "Orb of Regret"),
    "The Immortal": (1 / 90, "Mirror of Kalandra"),
    "The Hoarder": (1 / 12, EXALTED_ORB),
    "No Traces": (30 / 9, ORB_OF_SCOURING),
    "Lucky Deck": (10 / 9, "Stacked Deck"),
    "Alluring Bounty": (10 / 7, EXALTED_ORB),
    "The Scout": (8 / 7, EXALTED_ORB),
    "Abandoned Wealth": (3 / 5, EXALTED_ORB),
    "Underground Forest": (10 / 4, "Awakened Sextant"),
    "Three Faces in the Dark": (3 / 7, CHAOS),
    "The Scholar": (40 / 3, "Scroll of Wisdom"),
    "The Catalyst": (3 / 4, VAAL_ORB),
    "Lucky Connections": (20 / 7, FUSING),
    "Loyalty": (3 / 5, FUSING),
    "Boon of Justice": (1 / 6, "Offering to the Goddess"),
    "Sambodhi's Wisdom": (1 / 3, "A Master Seeks Help, Jun"),
    "The Cartographer": (10 / 1, CHISEL),
    "Gemcutter's Promise": (1 / 3, PRISM),
    "Coveted Possession": (5 / 9, "Regal Orb"),
    "Vile Power": (1 / 5, "Ancient Doom"),
    "The Union": (10 / 7, PRISM),
    "The Gemcutter": (1 / 3, PRISM),
    "Grave Knowledge": (1 / 6, PRISM),
    "Vinia's Token": (10 / 5, REGRET),
    "The Mad King": (1 / 7, "The King's Path"),
    "Dark Temptation": (1 / 5, "Obliteration"),
    "The Chains that Bind": (1 / 11,DIVINE),
    "Vanity": (1 / 9, DIVINE),
    "Humility": (1 / 9, DIVINE),
    "The Wrath": (10 / 8, CHAOS),
    "A Dab of Ink": (1 / 9, "The Poet's Pen"),
    "The Sun": (1 / 7, "Rise of the Phoenix"),
    "The Realm": (1 / 5, "Portal"),
    "The Blazing Fire": (1 / 8, "Chin Sol"),
    "The Jeweller's Boon": (1 / 5, "The Jeweller's Touch"),
    "The Valley of Steel Boxes": (1 / 9, "Monstrous Treasure"),
    "The Porcupine": (1 / 6, DIVINE),
    "The Betrayal": (1 / 9, "Maligaro's Virtuosity"),
    "The Dark Mage": (1 / 6, DIVINE),
    "The Warlord": (1 / 6, DIVINE),
    "Bowyer's Dream": (1 / 6, DIVINE),
    "The Sacrifice": (1 / 4, DIVINE),
    "The Celestial Justicar": (1 / 6, DIVINE),
    "The Dapper Prodigy": (1 / 6, DIVINE),
    "Emperor of Purity": (1 / 7, DIVINE),
    "The Ethereal": (1 / 7, DIVINE),
    "Acclimatisation": (20 / 2, ALTERATION),
    "A Sea of Blue": (13 / 3, ALTERATION),
    "The Polymath": (1 / 3, "Astramentis"),
    "The Offering": (1 / 6, "Shavronne's Wrappings"),
    "The Survivalist": (7 / 3, ALCHEMY),
    "Demigod's Wager": (1 / 7, "Orb of Annulment"),
    "Society's Remorse": (10 / 1, ALTERATION),
    "Brush, Paint and Palette": (1 / 5, "The Artist"),
    "Chaotic Disposition": (5 / 1, CHAOS),
    "The Heroic Shot": (17, CHROMATIC),
    "The Fool": (20 / 4, "Orb of Chance"),
    "Rain of Chaos": (1 / 8, CHAOS),
    "Last Hope": (1, "Mortal Hope"),
    "Rebirth": (1 / 27, "Oni Goroshi"),
    "The Seeker": (3 / 9, "Orb of Annulment"),
    "The Offspring": (1 / 9, "Ryslatha's Coil"),
    "The Whiteout": (1 / 8, "Cospri's Malice"),
    "The Craving": (1 / 4, "Unending Hunger"),
    "The Queen": ((1 / 16), "Atziri's Acuity"),
    "The Harvester": ((1 / 11), "The Harvest"),
    "Reckless Ambition": ((1 / 6), "Omeyocan"),
    "The Darkest Dream": ((1 / 6), "Severed in Sleep"),
    # "The Professor": ((1 / 4), "The Putrid Cloister"),
    "The Wolven King's Bite": ((1 / 8), "Rigwald's Quills"),
    "The Wind": ((1 / 7), "Windripper"),
    "The Pact": ((1 / 9), "Pledge of Hands"),
    "The King's Heart": ((1 / 8), "Kaom's Heart"),
    "The Endless Darkness": ((1 / 9), "Voidforge"),
    "The Prince of Darkness": ((1 / 6), "Elegant Hubris"),
    "The Master": ((1 / 4), "Bisco's Collar"),
    "Desperate Crusade": ((1 / 3), "Prism Guardian"),
    "Brotherhood in Exile": ((1 / 5), "One With Nothing"),
    "The Progeny of Lunaris": ((1 / 2), "Dying Sun"),
    "The Escape": ((1 / 5), "Seven-League Step"),
    "The World Eater": ((1 / 8), "Starforge"),
    "The Soul": ((1 / 9), "Soul Taker"),
    "The Risk": ((1 / 3), "Ventor's Gamble"),
    "The Doctor": ((1 / 8), "Headhunter"),
    "The Nurse": ((1 / 64), "Headhunter"),
    "Love Through Ice": ((1 / 4), "Unnatural Instinct"),
    "Mawr Blaidd": ((1 / 16), "Eyes of the Greatwolf"),
    "The Spark and the Flame": ((1 / 2), "Berek's Respite"),
    "The Vast": ((1 / 7), "Song of the Sirens"),
    "Hunter's Reward": ((1 / 3), "The Taming"),
    "Succor of the Sinless": ((1 / 6), "Bottled Faith"),
    "Eternal Bonds": ((1 / 4), "Replica Cortex"),
    "The Damned": ((1 / 6), "Soul Ripper"),
    "Pride of the First Ones": ((1 / 7), "Farrul's Fur"),
    "The Life Thief": ((1 / 6), "Zerphi's Heart"),
}

blacklist = [
    "The One With All",
    "A Mother's Parting Gift",
    "The Brittle Emperor",
    "The Master Artisan",
    "Tranquillity",
    "Amber Oil",
    "The Opulent",
    "The Mind's Eyes",
    "Divine Justice",
    "Anarchy's Price",
    "Assassin's Favour",
    "Boundless Realms",
    "Cartographer's Delight",
    "Clear Oil",
    "Cursed Words",
    "Death",
    "Doedre's Madness",
    "Friendship",
    "Gift of the Gemling Queen",
    "Her Mask",
    "Hunter's Resolve",
    "Imperial Legacy",
    "Lantador's Lost Love",
    "Light and Truth",
    "Lingering Remnants",
    "Might is Right",
    "Prosperity",
    "Rain Tempter",
    "Rats",
    "Scholar of the Seas",
    "Sepia Oil",
    "Struck by Lightning",
    "The Archmage's Right Hand",
    "The Arena Champion",
    "The Battle Born",
    "The Bear Woman",
    "The Beast",
    "The Body",
    "The Calling",
    "The Easy Stroll",
    "The Endurance",
    "The Eye of the Dragon",
    "The Flora's Gift",
    "The Gambler",
    "The Penitent",
    "The Garish Power",
    "The Gentleman",
    "The Gladiator",
    "The Hermit",
    "The Incantation",
    "The Inoculated",
    "The Journalist",

    "The Sword King's Salute",
    "The King's Blade",
    "The Long Watch",
    "The Lover",
    "The Lord of Celebration",
    "The Lion",
    "The Lich",
    "The Last Supper",
    "The Last One Standing",
    "The Journey",
    "The Jester",
    "The Hunger",
    "The Lunaris Priestess",
    "The Metalsmith's Gift",
    "The Mountain",
    "The Oath",
    "The Scarred Meadow",
    "The Sigil",
    "The Siren",
    "The Stormcaller",
    "The Summoner",
    "The Surgeon",
    "The Tower",
    "The Traitor",
    "The Tumbleweed",
    "The Twins",
    "The Warden",
    "The Watcher",
    "The Web",
    "The Witch",
    "The Wolf's Legacy",
    "The Wolf's Shadow",
    "The Wolverine",
    "Thirst for Knowledge",
    "Thunderous Skies",
    "Turn the Other Cheek",
    "Volatile Power",
    "Audacity",
    "Blind Venture",
    "Destined to Crumble",
    "Dialla's Subjugation",
    "Earth Drinker",
    "Glimmer of Hope",
    "Grave Knowledge",
    "Heterochromia",
    "Hope",
    "Hubris",
    "Jack in the Box",
    "Lost Worlds",
    "Lysah's Respite",
    "Shard of Fate",
    "The Aesthete",
    "The Carrion Crow",
    "The Cataclysm",
    "The Conduit",
    "The Cursed King",
    "The Demoness",
    "The Doppelganger",
    "The Dragon",
    "The Drunken Aristocrat",
    "The Encroaching Darkness",
    "The Explorer",
    "The Feast",
    "The Fletcher",
    "The Formless Sea",
    "The Fox",
    "The Pack Leader",
    "The Rabid Rhoa",
    "The Scavenger",
    "The Scholar",
    "The Sun",
    "The Surveyor",
    "The Visionary",
    "The Wolf",
    "Treasure Hunter",
    "Turn the Other Cheek",
    "Mitts",
    "Call to the First Ones",
    "The Coming Storm",
    "The Standoff",
    "The Forsaken",
    "Atziri's Arsenal",
    "The Blazing Fire",
    "The Ruthless Ceinture",
    "The Deceiver",
    "Forbidden Power",
    "The Breach",
    "Three Voices",
    "The Army of Blood",
    "The Sword King's Salute",
    "The Fathomless Depths",
    "The Rite of Elements",
    "The Dreamland",
    "The Admirer",
    "The Twilight Moon",
    "The Price of Protection",
    "A Dab of Ink",
    "The Mad King",
    "Alone in the Darkness",
    "Dark Temptation",
    "The Messenger",
    "Echoes of Love",
    "The Deep Ones",
    "Buried Treasure",
    "Vile Power",
    "The Skeleton",
    "Akil's Prophecy",
    "The Deal",
    "Cameria's Cut",
    "The Cache",
    "Prejudice",
    "The Adventuring Spirit",
    "The Blessing of Moosh",
    "The Fox in the Brambles",
    "The Unexpected Prize",
    "The Side Quest",
    "Boon of the First Ones",
    "Boon of Justice",
]
