conversion={'Abrasive Catalyst': 'abrasive-catalyst',
 'Ancient Orb': 'ancient-orb',
 'Ancient Reliquary Key': 'ancient-reliquary-key',
 'Annulment Shard': 'annulment-shard',
 "Apprentice Cartographer's Seal": None,
 "Armourer's Scrap": 'scr',
 'Awakened Sextant': 'master-sextant',
 "Awakener's Orb": None,
 "Blacksmith's Whetstone": 'whe',
 'Blessed Orb': 'blessed',
 'Blessing of Chayula': 'blessing-chayula',
 'Blessing of Esh': 'blessing-esh',
 'Blessing of Tul': 'blessing-tul',
 'Blessing of Uul-Netol': 'blessing-uul-netol',
 'Blessing of Xoph': 'blessing-xoph',
 "Cartographer's Chisel": 'chisel',
 'Chaos Orb': 'chaos',
 "Chayula's Breachstone": 'chayulas-breachstone',
 "Chayula's Charged Breachstone": 'chayulas-charged-breachstone',
 "Chayula's Enriched Breachstone": 'chayulas-enriched-breachstone',
 "Chayula's Pure Breachstone": 'chayulas-pure-breachstone',
 'Chromatic Orb': 'chrom',
 "Crusader's Exalted Orb": None,
 'Divine Orb': 'divine',
 'Divine Vessel': 'divine-vessel',
 "Eber's Key": 'eber',
 "Engineer's Orb": 'engineers-orb',
 "Esh's Breachstone": 'eshs-breachstone',
 "Esh's Charged Breachstone": 'eshs-charged-breachstone',
 "Esh's Enriched Breachstone": 'eshs-enriched-breachstone',
 "Esh's Pure Breachstone": 'eshs-pure-breachstone',
 'Eternal Orb': 'ete',
 'Exalted Orb': 'exa',
 'Exalted Shard': 'exalted-shard',
 'Fertile Catalyst': 'fertile-catalyst',
 'Fragment of Constriction': 'fragment-of-constriction',
 'Fragment of Emptiness': 'fragment-of-emptiness',
 'Fragment of Enslavement': 'fragment-of-enslavement',
 'Fragment of Eradication': 'fragment-of-eradication',
 'Fragment of Knowledge': 'fragment-of-knowledge',
 'Fragment of Purification': 'fragment-of-purification',
 'Fragment of Shape': 'fragment-of-shape',
 'Fragment of Terror': 'fragment-of-terror',
 'Fragment of the Chimera': 'chimer',
 'Fragment of the Hydra': 'hydra',
 'Fragment of the Minotaur': 'minot',
 'Fragment of the Phoenix': 'phoenix',
 "Gemcutter's Prism": 'gcp',
 "Glassblower's Bauble": 'ba',
 "Harbinger's Orb": 'harbingers-orb',
 "Hunter's Exalted Orb": None,
 'Imbued Catalyst': 'imbued-catalyst',
 'Intrinsic Catalyst': 'intrinsic-catalyst',
 "Inya's Key": 'inya',
 "Jeweller's Orb": 'jew',
 "Journeyman Cartographer's Seal": None,
 "Master Cartographer's Seal": None,
 'Mirror Shard': 'mirror-shard',
 'Mirror of Kalandra': 'mir',
 'Mortal Grief': 'grie',
 'Mortal Hope': 'hope',
 'Mortal Ignorance': 'ign',
 'Mortal Rage': 'rage',
 'Mortal Set': 'mortal-set',
 'Offering to the Goddess': 'offer',
 'Orb of Alchemy': 'alch',
 'Orb of Alteration': 'alt',
 'Orb of Annulment': 'orb-of-annulment',
 'Orb of Augmentation': 'aug',
 'Orb of Binding': 'orb-of-binding',
 'Orb of Chance': 'chance',
 'Orb of Fusing': 'fuse',
 'Orb of Horizons': 'orb-of-horizons',
 'Orb of Regret': 'regret',
 'Orb of Scouring': 'scour',
 'Orb of Transmutation': 'tra',
 'Pale Court Set': 'pale-court-set',
 'Perandus Coin': 'p',
 'Portal Scroll': 'port',
 'Prime Sextant': 'journeyman-sextant',
 'Prismatic Catalyst': 'prismatic-catalyst',
 "Redeemer's Exalted Orb": None,
 'Regal Orb': 'regal',
 'Sacrifice Set': 'sacrifice-set',
 'Sacrifice at Dawn': 'dawn',
 'Sacrifice at Dusk': 'dusk',
 'Sacrifice at Midnight': 'mid',
 'Sacrifice at Noon': 'noon',
 'Scroll of Wisdom': 'wis',
 'Shaper Set': None,
 'Silver Coin': 'silver',
 'Simple Sextant': 'apprentice-sextant',
 'Simulacrum': 'simulacrum',
 'Simulacrum Splinter': 'simulacrum-splinter',
 'Splinter of Chayula': 'splinter-chayula',
 'Splinter of Esh': 'splinter-esh',
 'Splinter of Tul': 'splinter-tul',
 'Splinter of Uul-Netol': 'splinter-uul',
 'Splinter of Xoph': 'splinter-xoph',
 'Stacked Deck': 'stacked-deck',
 'Tempering Catalyst': 'tempering-catalyst',
 'Timeless Eternal Emblem': 'timeless-eternal-emblem',
 'Timeless Eternal Empire Splinter': 'timeless-eternal-empire-splinter',
 'Timeless Karui Emblem': 'timeless-karui-emblem',
 'Timeless Karui Splinter': 'timeless-karui-splinter',
 'Timeless Maraketh Emblem': 'timeless-maraketh-emblem',
 'Timeless Maraketh Splinter': 'timeless-maraketh-splinter',
 'Timeless Templar Emblem': 'timeless-templar-emblem',
 'Timeless Templar Splinter': 'timeless-templar-splinter',
 'Timeless Vaal Emblem': 'timeless-vaal-emblem',
 'Timeless Vaal Splinter': 'timeless-vaal-splinter',
 'Timeworn Reliquary Key': 'timeworn-reliquary-key',
 "Tul's Breachstone": 'tuls-breachstone',
 "Tul's Charged Breachstone": 'tuls-charged-breachstone',
 "Tul's Enriched Breachstone": 'tuls-enriched-breachstone',
 "Tul's Pure Breachstone": 'tuls-pure-breachstone',
 'Turbulent Catalyst': 'turbulent-catalyst',
 "Uul-Netol's Breachstone": 'uul-breachstone',
 "Uul-Netol's Charged Breachstone": 'uul-charged-breachstone',
 "Uul-Netol's Enriched Breachstone": 'uul-enriched-breachstone',
 "Uul-Netol's Pure Breachstone": 'uul-pure-breachstone',
 'Vaal Orb': 'vaal',
 "Volkuur's Key": 'volkuur',
 "Warlord's Exalted Orb": None,
 "Xoph's Breachstone": 'xophs-breachstone',
 "Xoph's Charged Breachstone": 'xophs-charged-breachstone',
 "Xoph's Enriched Breachstone": 'xophs-enriched-breachstone',
 "Xoph's Pure Breachstone": 'xophs-pure-breachstone',
 "Yriel's Key": 'yriel'}