from constants import (
    EXALTED_ORB,
    VAAL_ORB,
    ORB_OF_SCOURING,
    CHAOS,
    FUSING,
    CHISEL,
    PRISM,
    REGRET,
    DIVINE,
    ALTERATION,
    ALCHEMY,
    CHROMATIC,
)

currency_shards = {
    "House of Mirrors": ((1 / 9), "Mirror of Kalandra"),
    "Seven Years Bad Luck": (1 / 13, "Mirror Shard"),
    "Unrequited Love": (19 / (20 * 16), "Mirror of Kalandra"),
    "The Sephirot": (11 / 10, "Divine Orb"),
    "The Saint's Treasure": (2 / 10, EXALTED_ORB),
    "The Inventor": (10 / 6, VAAL_ORB),
    "The Innocent": (40 / 10, "Orb of Regret"),
    "The Immortal": (1 / 90, "Mirror of Kalandra"),
    "The Hoarder": (1 / 12, EXALTED_ORB),
    "No Traces": (30 / 9, ORB_OF_SCOURING),
    "Lucky Deck": (10 / 9, "Stacked Deck"),
    "Alluring Bounty": (10 / 7, EXALTED_ORB),
    "The Scout": (7 / 8, EXALTED_ORB),
    "Abandoned Wealth": (3 / 5, EXALTED_ORB),
    "Underground Forest": (10 / 4, "Awakened Sextant"),
    "Three Faces in the Dark": (3 / 7, CHAOS),
    "The Scholar": (40 / 3, "Scroll of Wisdom"),
    "The Catalyst": (3 / 4, VAAL_ORB),
    "Lucky Connections": (20 / 7, FUSING),
    "Loyalty": (3 / 5, FUSING),
    "Boon of Justice": (1 / 6, "Offering to the Goddess"),
    "Sambodhi's Wisdom": (1 / 3, "A Master Seeks Help, Jun"),
    "The Cartographer": (10 / 1, CHISEL),
    "Gemcutter's Promise": (1 / 3, PRISM),
    "Coveted Possession": (5 / 9, "Regal Orb"),
    "Vile Power": (1 / 5, "Ancient Doom"),
    "The Union": (10 / 7, PRISM),
    "The Gemcutter": (1 / 3, PRISM),
    "Grave Knowledge": (1 / 6, PRISM),
    "Vinia's Token": (10 / 5, REGRET),
    "The Mad King": (1 / 7, "The King's Path"),
    "Dark Temptation": (1 / 5, "Obliteration"),
    "The Chains that Bind": (1 / 11, DIVINE),
    "Immortal Resolve": (1 / 6, DIVINE),
    "Vanity": (1 / 9, DIVINE),
    "Humility": (1 / 9, DIVINE),
    "The Wrath": (10 / 8, CHAOS),
    "A Dab of Ink": (1 / 9, "The Poet's Pen"),
    "The Sun": (1 / 7, "Rise of the Phoenix"),
    "The Realm": (1 / 5, "Portal"),
    "The Blazing Fire": (1 / 8, "Chin Sol"),
    "The Valley of Steel Boxes": (1 / 9, "Monstrous Treasure"),
    "The Porcupine": (1 / 6, DIVINE),
    "The Betrayal": (1 / 9, "Maligaro's Virtuosity"),
    "The Dark Mage": (1 / 6, DIVINE),
    "The Warlord": (1 / 6, DIVINE),
    "Bowyer's Dream": (1 / 6, DIVINE),
    "The Sacrifice": (1 / 4, DIVINE),
    "The Celestial Justicar": (1 / 6, DIVINE),
    "The Dapper Prodigy": (1 / 6, DIVINE),
    "Emperor of Purity": (1 / 7, DIVINE),
    "The Ethereal": (1 / 7, DIVINE),
    "Acclimatisation": (20 / 2, ALTERATION),
    "A Sea of Blue": (13 / 3, ALTERATION),
    "The Polymath": (1 / 3, "Astramentis"),
    "The Offering": (1 / 6, "Shavronne's Wrappings"),
    "The Survivalist": (7 / 3, ALCHEMY),
    "Demigod's Wager": (1 / 7, "Orb of Annulment"),
    "Society's Remorse": (10 / 1, ALTERATION),
    "Brush, Paint and Palette": (1 / 5, "The Artist"),
    "Chaotic Disposition": (5 / 1, CHAOS),
    "The Heroic Shot": (17, CHROMATIC),
    "The Fool": (20 / 4, "Orb of Chance"),
    "Rain of Chaos": (1 / 8, CHAOS),
    "Last Hope": (1, "Mortal Hope"),
    "Rebirth": (1 / 27, "Oni Goroshi"),
    "The Seeker": (3 / 9, "Orb of Annulment"),
    "The Offspring": (1 / 9, "Ryslatha's Coil"),
    "The Whiteout": (1 / 8, "Cospri's Malice"),
    "The Craving": (1 / 4, "Unending Hunger"),
    "The Queen": ((1 / 16), "Atziri's Acuity"),
    "The Harvester": ((1 / 11), "The Harvest"),
    "Reckless Ambition": ((1 / 6), "Omeyocan"),
    "The Darkest Dream": ((1 / 6), "Severed in Sleep"),
    # "The Professor": ((1 / 4), "The Putrid Cloister"),
    "The Wolven King's Bite": ((1 / 8), "Rigwald's Quills"),
    "The Wind": ((1 / 7), "Windripper"),
    "The Pact": ((1 / 9), "Pledge of Hands"),
    "The King's Heart": ((1 / 8), "Kaom's Heart"),
    "The Endless Darkness": ((1 / 9), "Voidforge"),
    "The Prince of Darkness": ((1 / 6), "Elegant Hubris"),
    "The Master": ((1 / 4), "Bisco's Collar"),
    "Desperate Crusade": ((1 / 3), "Prism Guardian"),
    "Brotherhood in Exile": ((1 / 5), "One With Nothing"),
    "The Progeny of Lunaris": ((1 / 2), "Dying Sun"),
    "The Escape": ((1 / 5), "Seven-League Step"),
    "The World Eater": ((1 / 8), "Starforge"),
    "The Soul": ((1 / 9), "Soul Taker"),
    "The Risk": ((1 / 3), "Ventor's Gamble"),
    "The Doctor": ((1 / 8), "Headhunter"),
    "The Nurse": ((1 / 64), "Headhunter"),
    "Love Through Ice": ((1 / 4), "Unnatural Instinct"),
    "Mawr Blaidd": ((1 / 16), "Eyes of the Greatwolf"),
    "The Spark and the Flame": ((1 / 2), "Berek's Respite"),
    "The Vast": ((1 / 7), "Song of the Sirens"),
    "Hunter's Reward": ((1 / 3), "The Taming"),
    "Succor of the Sinless": ((1 / 6), "Bottled Faith"),
    "Eternal Bonds": ((1 / 4), "Replica Cortex"),
    "The Damned": ((1 / 6), "Soul Ripper"),
    "Pride of the First Ones": ((1 / 7), "Farrul's Fur"),
    "The Life Thief": ((1 / 6), "Zerphi's Heart"),
    "Beauty Through Death": (1 / 5, "Atziri's Reflection"),
    "A Note in the Wind": (1 / 4, "Asenath's Chant"),
    # "Silence and Frost":(1/7,'The Pandemonius'),
# "Judging Voices":(1/9,"Forbidden Shako"),

}
